name: dendrite
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - h5py
  - pytorch
  - cython
  - numba
  - dask
  - dask-jobqueue
  - pip
  - pip:
    - opensimplex
    - edt
    - connected-components-3d
    - pyunionfind
    - git+https://github.com/donglaiw/ImUtil.git
