chunk_size: [512, 512, 512]
output_dir: "outputs"
n_jobs_precompute: 128
n_jobs_skeletonize: 32
n_jobs_mesh: 32
n_jobs_touching_centroids: 32
n_jobs_feature_transform: 8
n_jobs_pc: 32

skeletonize_trunk:
  mip: 0
  shape: ${chunk_size}
  sharded: False
  dust_threshold: 0
  progress: True
  parallel: 1
  fill_missing: False
  teasar_params:
    scale: 1.5
    const: 10000
    soma_detection_threshold: 1500
    soma_acceptance_threshold: 3500
    soma_invalidation_scale: 2
    soma_invalidation_const: 300
    pdrf_scale: 100000
    pdrf_exponent: 4

skeletonize_spines:
  mip: 0
  shape: ${chunk_size}
  sharded: False
  dust_threshold: 0
  progress: True
  parallel: 1
  fill_missing: False
  teasar_params:
    scale: 1.5
    const: 300
    soma_detection_threshold: 1500
    soma_acceptance_threshold: 3500
    soma_invalidation_scale: 2
    soma_invalidation_const: 300
    pdrf_scale: 100000
    pdrf_exponent: 4

skeletonize_merge:
  crop: 0
  magnitude: 3
  dust_threshold: 0
  tick_threshold: 3500
  delete_fragments: False

mesh:
  mip: 0
  shape: ${chunk_size}
  sharded: False
  progress: True
  spatial_index: False
  # waiting for this to resolve
  # https://github.com/seung-lab/igneous/pull/178
  mesh_dir: mesh

mesh_merge:
  magnitude: 3
  mesh_dir: mesh

touching_centroids:
  connectivity: 6

feature_transform:
  radii_multiplier: 2.0

point_cloud:
  chunk_size: 4096

dataloader:
  path_length: 10000
