name: human
anisotropy: [30, 8, 8]
_base_dir: "/mmfs1/data/adhinart/dendrite"
data:
  raw: ${_base_dir}/raw/${name}_raw.h5
  raw_key: "main"
  spine: ${_base_dir}/raw/${name}_spine.h5
  spine_key: "main"
  seg: ${_base_dir}/raw/${name}_seg.h5
  seg_key: "main"
  output_layer: ${output_dir}/${name}/output_layer
  mapping: ${output_dir}/${name}/mapping.npy
  touching: ${output_dir}/${name}/touching.npz
  seed: ${output_dir}/${name}/seed.npz
  seed_zarr: ${output_dir}/${name}/seed.zarr
  seed_zarr_sync: ${output_dir}/${name}/seed.sync
  feature_zarr: ${output_dir}/${name}/feature.zarr
  feature_zarr_sync: ${output_dir}/${name}/feature.sync
  pc_zarr: ${output_dir}/${name}/pc.zarr
  pc_zarr_sync: ${output_dir}/${name}/pc_sync.zarr
