name: seg_den
anisotropy: [30, 6, 6]
_base_dir: "/mmfs1/data/adhinart/dendrite"
data:
  raw: ${_base_dir}/raw/${name}_raw.h5
  raw_key: "main"
  spine: ${_base_dir}/raw/${name}_spine.h5
  spine_key: "main"
  seg: ${_base_dir}/raw/${name}_seg.h5
  seg_key: "main"
  output_layer: ${output_dir}/${name}/output_layer
  mapping : ${output_dir}/${name}/mapping.npy
  touching: ${output_dir}/${name}/touching.npz
