name: seg_den
anisotropy: [30, 6, 6]
_base_dir: "/mmfs1/data/adhinart/dendrite"

skeletonize_trunk:
  teasar_params:
    - ids:
        [
          1,
          2,
          3,
          4,
          5,
          8,
          9,
          11,
          12,
          13,
          14,
          15,
          17,
          19,
          20,
          21,
          23,
          24,
          26,
          27,
          28,
          30,
          32,
          33,
          35,
          37,
          38,
          39,
          40,
          41,
          42,
          43,
          44,
          45,
          46,
          47,
          48,
          50,
        ]
      mip: 4
      const: 10000
      scale: 1.5
    - ids: [7, 10, 18, 25, 31, 36, 49, 16]
      mip: 4
      const: 5000
      scale: 1.5
    - ids: [6, 22, 29, 34]
      mip: 4
      const: 2000
      scale: 1.5

skeletonize_spines:
  teasar_params:
    - mip: 0
      const: 150
      scale: 1.5

data:
  broken_debug: ${output_dir}/${name}/broken_debug.npz

  broken_raw: ${_base_dir}/raw/${name}_raw.h5
  broken_raw_key: "main"
  broken_spine: ${_base_dir}/raw/${name}_spine.h5
  broken_spine_key: "main"
  broken_seg: ${_base_dir}/raw/${name}_seg.h5
  broken_seg_key: "main"
  broken_new_branches:
    - trunk_id: 16
      file: ${_base_dir}/raw/seg_d5_6nm.h5
      key: "main"
    - trunk_id: 31
      file: ${_base_dir}/raw/seg_d31_6nm.h5
      key: "main"

  raw: ${_base_dir}/raw/${name}_raw_fixed.h5
  raw_key: "main"
  spine: ${_base_dir}/raw/${name}_spine_fixed.h5
  spine_key: "main"
  seg: ${_base_dir}/raw/${name}_seg_fixed.h5
  seg_key: "main"

  output_layer: ${output_dir}/${name}/output_layer
  mapping: ${output_dir}/${name}/mapping.npy
  touching: ${output_dir}/${name}/touching.npz
  seed: ${output_dir}/${name}/seed.npz
  seed_zarr: ${output_dir}/${name}/seed.zarr
  seed_zarr_sync: ${output_dir}/${name}/seed.sync
  feature_zarr: ${output_dir}/${name}/feature.zarr
  feature_zarr_sync: ${output_dir}/${name}/feature.sync
  pc_zarr: ${output_dir}/${name}/pc.zarr
  pc_zarr_sync: ${output_dir}/${name}/pc_sync.zarr
  pc_lengths: ${output_dir}/${name}/pc_lengths.npz

# import numpy as np
# np.random.seed(0)
# numbers = np.random.permutation(range(1, 51))
# split_lists = [sorted(x) for x in np.array_split(numbers, 5)]
dataloader:
  folds:
    - [3, 5, 11, 12, 23, 28, 29, 32, 39, 42]
    - [8, 15, 19, 27, 30, 34, 35, 36, 46, 49]
    - [9, 14, 16, 17, 21, 26, 31, 33, 43, 44]
    - [2, 6, 7, 13, 18, 24, 25, 38, 41, 50]
    - [1, 4, 10, 20, 22, 37, 40, 45, 47, 48]
  cached:
    - num_points: 1000000
      path_length: 10000
      output_dir: ${output_dir}/${name}/dataset_${dataloader.cached[0].num_points}_${dataloader.cached[0].path_length}
    - num_points: 1000000
      path_length: 20000
      output_dir: ${output_dir}/${name}/dataset_${dataloader.cached[1].num_points}_${dataloader.cached[1].path_length}
