from chunk_pipeline.tasks.loadh5 import task_load_h5
from chunk_pipeline.tasks.generate_bboxes import task_bbox
from chunk_pipeline.tasks.coarse import task_generate_original, task_coarse_segment
from chunk_pipeline.tasks.extract_seg import task_extract_seg
from chunk_pipeline.tasks.generate_skeleton import task_skeletonize
from chunk_pipeline.tasks.point import task_generate_point_cloud
from chunk_pipeline.tasks.foundation import task_foundation_seg
